// build.rs
//
// Generates one #[test] per file in tests/corpus/. Each test calls
// `crate::corpus_support::run_one` with the path to its .gol file.
//
// Adding a new corpus program requires no changes to test code —
// cargo re-runs this script when tests/corpus/ changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Rerun when the corpus directory changes. Cargo watches the
    // whole directory tree for `rerun-if-changed` on a directory.
    println!("cargo:rerun-if-changed=tests/corpus");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest = PathBuf::from(out_dir).join("corpus_generated.rs");

    let corpus_dir = Path::new("tests/corpus");
    let mut entries: Vec<PathBuf> = if corpus_dir.is_dir() {
        fs::read_dir(corpus_dir)
            .expect("cannot read tests/corpus/")
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("gol"))
            .collect()
    } else {
        Vec::new()
    };
    entries.sort();

    let mut out = String::new();
    out.push_str("// Generated by build.rs from tests/corpus/*.gol.\n");
    out.push_str("// Do not edit — add or remove .gol files instead.\n\n");

    if entries.is_empty() {
        out.push_str("// No corpus files found.\n");
    }

    for entry in &entries {
        let stem = entry
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unnamed");
        let mut ident = String::new();
        for c in stem.chars() {
            if c.is_alphanumeric() || c == '_' {
                ident.push(c);
            } else {
                ident.push('_');
            }
        }
        if ident.is_empty() || ident.chars().next().map_or(true, |c| c.is_ascii_digit()) {
            ident.insert(0, '_');
        }
        let path_str = entry.to_string_lossy().replace('\\', "/");

        out.push_str(&format!(
            "#[test]\nfn {}() {{\n    if let Err(e) = crate::corpus_support::run_one({:?}) {{\n        panic!(\"{{}}\", e);\n    }}\n}}\n\n",
            ident, path_str
        ));
    }

    fs::write(&dest, out).expect("cannot write generated corpus test file");
}
