#!/usr/bin/env python3
"""
Phase 6: split corpus_diff.rs into per-program tests.

Creates:
  build.rs                         — generates one #[test] per corpus file
  tests/corpus_support/mod.rs      — shared harness logic
  tests/corpus_diff.rs             — rewritten as a shim

Idempotent: safe to re-run; overwrites the three files above.
"""

import sys
from pathlib import Path


BUILD_RS = r'''// build.rs
//
// Generates one #[test] per file in tests/corpus/. Each test calls
// `crate::corpus_support::run_one` with the path to its .gol file.
//
// Adding a new corpus program requires no changes to test code —
// cargo re-runs this script when tests/corpus/ changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Rerun when the corpus directory changes. Cargo watches the
    // whole directory tree for `rerun-if-changed` on a directory.
    println!("cargo:rerun-if-changed=tests/corpus");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest = PathBuf::from(out_dir).join("corpus_generated.rs");

    let corpus_dir = Path::new("tests/corpus");
    let mut entries: Vec<PathBuf> = if corpus_dir.is_dir() {
        fs::read_dir(corpus_dir)
            .expect("cannot read tests/corpus/")
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("gol"))
            .collect()
    } else {
        Vec::new()
    };
    entries.sort();

    let mut out = String::new();
    out.push_str("// Generated by build.rs from tests/corpus/*.gol.\n");
    out.push_str("// Do not edit — add or remove .gol files instead.\n\n");

    if entries.is_empty() {
        out.push_str("// No corpus files found.\n");
    }

    for entry in &entries {
        let stem = entry
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unnamed");
        let mut ident = String::new();
        for c in stem.chars() {
            if c.is_alphanumeric() || c == '_' {
                ident.push(c);
            } else {
                ident.push('_');
            }
        }
        if ident.is_empty() || ident.chars().next().map_or(true, |c| c.is_ascii_digit()) {
            ident.insert(0, '_');
        }
        let path_str = entry.to_string_lossy().replace('\\', "/");

        out.push_str(&format!(
            "#[test]\nfn {}() {{\n    if let Err(e) = crate::corpus_support::run_one({:?}) {{\n        panic!(\"{{}}\", e);\n    }}\n}}\n\n",
            ident, path_str
        ));
    }

    fs::write(&dest, out).expect("cannot write generated corpus test file");
}
'''

CORPUS_SUPPORT = r'''// tests/corpus_support/mod.rs
//
// Shared harness for the per-program corpus tests generated by
// build.rs. Each generated #[test] calls `run_one` with the path to
// its .gol file.
//
// Uses `CARGO_BIN_EXE_algol26` (set by Cargo for integration tests)
// rather than `cargo run`:
//   * `cargo run` acquires the target-directory lock, so parallel
//     tests would serialize on it.
//   * Skipping the cargo subprocess roughly halves test-suite time
//     on a warm target directory.

use std::fs;
use std::path::Path;
use std::process::Command;

/// Run one corpus program and compare its output to the `// OUTPUT:`
/// annotations. Returns `Err` with a detailed message on failure.
pub fn run_one(path: &str) -> Result<(), String> {
    let path = Path::new(path);
    if !path.exists() {
        return Err(format!("corpus file not found: {}", path.display()));
    }
    let source = fs::read_to_string(path)
        .map_err(|e| format!("cannot read {}: {}", path.display(), e))?;

    let known_failure = source
        .lines()
        .any(|l| l.starts_with("// KNOWN_FAILURE"));

    // `// BACKEND: interpreter` matches the conformance harness.
    // Default is LLVM.
    let backend = source
        .lines()
        .find_map(|l| l.strip_prefix("// BACKEND: "))
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "llvm".to_string());

    let expected: Vec<&str> = source
        .lines()
        .filter_map(|l| l.strip_prefix("// OUTPUT: "))
        .collect();
    let expected = expected.join("\n");

    let compiler_bin = env!("CARGO_BIN_EXE_algol26");

    // Compile step (LLVM only — interpreter runs directly).
    if backend != "interpreter" {
        let out = Command::new(compiler_bin)
            .arg(path)
            .output()
            .map_err(|e| format!("failed to run compiler: {}", e))?;
        if !out.status.success() {
            // KNOWN_FAILURE means the compile failure is expected —
            // pass silently.
            if known_failure {
                return Ok(());
            }
            return Err(format!(
                "{}: COMPILE FAILED\n{}",
                path.display(),
                String::from_utf8_lossy(&out.stderr)
            ));
        }
    }

    // Run step.
    let actual = if backend == "interpreter" {
        let out = Command::new(compiler_bin)
            .args(["run", "--interpreter"])
            .arg(path)
            .output()
            .map_err(|e| format!("failed to run interpreter: {}", e))?;
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .filter(|l| !l.starts_with('['))
            .collect::<Vec<_>>()
            .join("\n")
            .trim_end()
            .to_string()
    } else {
        let binary = path.with_extension("");
        let out = Command::new(&binary)
            .output()
            .map_err(|e| format!("failed to execute {}: {}", binary.display(), e))?;
        String::from_utf8_lossy(&out.stdout).trim_end().to_string()
    };

    // Verdict.
    if known_failure {
        if actual == expected {
            return Err(format!(
                "{}: KNOWN_FAILURE now PASSES — remove the marker and celebrate",
                path.display()
            ));
        }
        return Ok(());
    }

    if actual != expected {
        return Err(format!(
            "{}: OUTPUT MISMATCH\nexpected:\n{}\nactual:\n{}",
            path.display(),
            expected,
            actual
        ));
    }
    Ok(())
}
'''

CORPUS_DIFF = r'''// tests/corpus_diff.rs
//
// Per-program corpus tests, generated at build time from
// tests/corpus/*.gol. The harness lives in `corpus_support`; the
// test functions themselves are in $OUT_DIR/corpus_generated.rs.

mod corpus_support;

include!(concat!(env!("OUT_DIR"), "/corpus_generated.rs"));
'''


def main():
    repo = Path.cwd()
    if not (repo / "Cargo.toml").exists():
        print("ERROR: run from repo root", file=sys.stderr)
        return 1

    (repo / "build.rs").write_text(BUILD_RS)
    print("  wrote: build.rs")

    support_dir = repo / "tests" / "corpus_support"
    support_dir.mkdir(parents=True, exist_ok=True)
    (support_dir / "mod.rs").write_text(CORPUS_SUPPORT)
    print("  wrote: tests/corpus_support/mod.rs")

    (repo / "tests" / "corpus_diff.rs").write_text(CORPUS_DIFF)
    print("  wrote: tests/corpus_diff.rs")

    print()
    print("Verify with:")
    print("  cargo test --test corpus_diff 2>&1 | tail -20")
    return 0


if __name__ == "__main__":
    sys.exit(main())