#!/usr/bin/env python3
"""
Generate docs/features/map.md.

Run from the repo root:
    python3 tools/gen_map_doc.py

Writes:
    docs/features/map.md

Prints the row to add to docs/IMPLEMENTATION_STATUS.md.
"""

from pathlib import Path

# ─────────────────────────────────────────────────────────────────────
# docs/features/map.md — user-facing feature doc
# ─────────────────────────────────────────────────────────────────────

FEATURE_MAP = [
    "# `Map<K, V>` — Key-Value Container",
    "",
    "**Status:** Interpreter complete. LLVM and WASM refuse programs",
    "that use maps; use `--interpreter` to run them.",
    "",
    "**ADR:** `docs/decisions/0027-map.md`",
    "",
    "## What it is",
    "",
    "A `Map<K, V>` stores values indexed by keys. Lookup, insertion,",
    "and membership tests are keyed operations — no linear scan, no",
    "parallel `List<K>` / `List<V>` pairs.",
    "",
    "Maps are the container the language was missing for anything",
    "keyed: config files, aggregation by column, CLI flag tables,",
    "flat JSON objects.",
    "",
    "```",
    "val counts := Map { \"a\": 1, \"b\": 2, \"c\": 3 }",
    "```",
    "",
    "## Syntax",
    "",
    "### Construction",
    "",
    "Literal with inferred types:",
    "",
    "```",
    "val m := Map { \"a\": 1, \"b\": 2 }      // Map<String, Int>",
    "```",
    "",
    "Literal with explicit type arguments:",
    "",
    "```",
    "val m := Map<String, Int> { \"a\": 1 }",
    "```",
    "",
    "Empty map, explicit type arguments:",
    "",
    "```",
    "val m := Map<String, Int> {}",
    "```",
    "",
    "Empty map, inferred from the surrounding annotation:",
    "",
    "```",
    "var m: Map<String, Int> := Map {}",
    "```",
    "",
    "An empty `Map {}` with no annotation and no explicit type",
    "arguments is a compile error — the analyzer has nothing to",
    "infer from.",
    "",
    "### Operations",
    "",
    "All operations are method-form. `insert` mutates; the rest read.",
    "",
    "```",
    "m.insert(k, v)      // mutating — requires `var m`",
    "m.get(k)            // -> Option<V>",
    "m.contains(k)       // -> Bool",
    "m.keys()            // -> List<K>",
    "m.values()          // -> List<V>",
    "m.length()          // -> Int",
    "```",
    "",
    "The zero-argument methods also work without parentheses:",
    "",
    "```",
    "print(m.length)     // same as m.length()",
    "print(m.keys)       // same as m.keys()",
    "```",
    "",
    "The argument-taking methods (`insert`, `get`, `contains`) require",
    "parentheses. Writing `m.get` without a call and without arguments",
    "produces a 'requires parentheses' diagnostic.",
    "",
    "### Iteration",
    "",
    "Iterate by taking the key list first:",
    "",
    "```",
    "for k in m.keys()",
    "    val v := m.get(k)",
    "    match v",
    "        case Some(x)",
    "            print(k + \": \" + to_string(x))",
    "        case None",
    "            print(k + \": <missing>\")",
    "```",
    "",
    "`keys()` and `values()` are both sorted by key, so",
    "`zip(m.keys(), m.values())` yields aligned `(k, v)` pairs.",
    "",
    "## Semantics",
    "",
    "### Key types",
    "",
    "Keys are restricted to `Int`, `String`, and `Bool`. Any other",
    "key type is a compile error:",
    "",
    "```",
    "val bad := Map<Float, Int> { 1.5: 1 }   // error",
    "```",
    "",
    "The restriction exists because Floats have no total equality",
    "(`NaN != NaN`), and records and lists have no user-definable",
    "hash function.",
    "",
    "### Value types",
    "",
    "Values are unrestricted. `Map<String, List<Int>>`, `Map<Int, Map<String, Bool>>`,",
    "and `Map<String, Point>` where `Point` is a record all work.",
    "",
    "### `insert` requires `var`",
    "",
    "```",
    "var m := Map<String, Int> {}",
    "m.insert(\"a\", 1)        // OK",
    "```",
    "",
    "```",
    "val m := Map<String, Int> {}",
    "m.insert(\"a\", 1)        // E0007: cannot call 'insert' on immutable variable",
    "```",
    "",
    "`insert` overwrites an existing key silently. To insert only if",
    "absent:",
    "",
    "```",
    "if not m.contains(k) then m.insert(k, v)",
    "```",
    "",
    "### `get` returns `Option<V>`",
    "",
    "```",
    "val x := m.get(\"a\")",
    "match x",
    "    case Some(v)",
    "        print(v)",
    "    case None",
    "        print(\"missing\")",
    "```",
    "",
    "`None` means the key is absent. A map whose values are themselves",
    "`Option` produces a nested Option, so `Some(None)` means 'key",
    "present, value is None' and `None` means 'key absent' — the two",
    "cases are unambiguous.",
    "",
    "### Iteration order",
    "",
    "Unspecified at the language level. `keys()` and `values()` are",
    "sorted by key in the current interpreter, so programs that",
    "iterate a Map get deterministic output today, but the language",
    "does not guarantee it. Programs that require a specific order",
    "should sort the key list explicitly.",
    "",
    "### Copy semantics",
    "",
    "`Map<K, V>` is never `Copy`. Maps own heap storage; assignment",
    "moves. This matches `List<T>`.",
    "",
    "## Backend support",
    "",
    "| Backend     | Support                                                |",
    "|-------------|--------------------------------------------------------|",
    "| Interpreter | Yes                                                    |",
    "| LLVM        | Refused — pass `--interpreter` to run                  |",
    "| WASM        | Refused — pass `--interpreter` to run                  |",
    "",
    "Running a Map program through LLVM produces:",
    "",
    "```",
    "error[E0002]: The LLVM backend does not support: Map<K, V> ...",
    "Run through the interpreter instead:",
    "    algol26 run --interpreter <file.gol>",
    "```",
    "",
    "## What is not in v1",
    "",
    "- `remove(k)` — deletion. Follow-up; the return type is the",
    "  open question (`Option<V>` vs `Bool`).",
    "- Ordered maps — no insertion-order guarantee.",
    "- Custom hash or equality — keys are limited to the three",
    "  builtin types.",
    "- Iteration directly over the map (`for (k, v) in m`).",
    "  Use `for k in m.keys()`.",
    "- `Map.entries()` — returning `List<(K, V)>` would need tuples,",
    "  which the language does not have.",
    "- LLVM lowering.",
    "",
    "## Example",
    "",
    "```",
    "procedure main",
    "    var counts := Map<String, Int> {}",
    "",
    "    val words := [\"apple\", \"banana\", \"apple\", \"cherry\", \"banana\", \"apple\"]",
    "    for w in words",
    "        val prev := counts.get(w)",
    "        match prev",
    "            case Some(n)",
    "                counts.insert(w, n + 1)",
    "            case None",
    "                counts.insert(w, 1)",
    "",
    "    for k in counts.keys()",
    "        val v := counts.get(k)",
    "        match v",
    "            case Some(n)",
    "                print(k + \": \" + to_string(n))",
    "            case None",
    "                print(k + \": <missing>\")",
    "```",
    "",
    "Output (sorted by key):",
    "",
    "```",
    "apple: 3",
    "banana: 2",
    "cherry: 1",
    "```",
    "",
    "## See also",
    "",
    "- `docs/decisions/0027-map.md` — design and rationale",
    "- `docs/features/record.md` — `rec` structured types",
    "- `docs/features/list.md` — ordered sequences",
    "- `docs/features/option.md` — `Map.get` returns `Option<V>`",
]

# ─────────────────────────────────────────────────────────────────────
# Row for docs/IMPLEMENTATION_STATUS.md (insert manually)
# ─────────────────────────────────────────────────────────────────────

STATUS_ROW = "| `Map<K, V>` | Interpreter | LLVM/WASM refused | ADR 0027 |"

def main() -> None:
    repo = Path(".")
    feat_path = repo / "docs" / "features" / "map.md"

    feat_path.write_text("\n".join(FEATURE_MAP) + "\n", encoding="utf-8")
    print(f"wrote {feat_path}  ({len(FEATURE_MAP)} lines)")

    print()
    print("Add this row to docs/IMPLEMENTATION_STATUS.md:")
    print()
    print("    " + STATUS_ROW)

if __name__ == "__main__":
    main()