// tests/corpus_support/mod.rs
//
// Shared harness for the per-program corpus tests generated by
// build.rs. Each generated #[test] calls `run_one` with the path to
// its .gol file.
//
// Uses `CARGO_BIN_EXE_algol26` (set by Cargo for integration tests)
// rather than `cargo run`:
//   * `cargo run` acquires the target-directory lock, so parallel
//     tests would serialize on it.
//   * Skipping the cargo subprocess roughly halves test-suite time
//     on a warm target directory.

use std::fs;
use std::path::Path;
use std::process::Command;

/// Run one corpus program and compare its output to the `// OUTPUT:`
/// annotations. Returns `Err` with a detailed message on failure.
pub fn run_one(path: &str) -> Result<(), String> {
    let path = Path::new(path);
    if !path.exists() {
        return Err(format!("corpus file not found: {}", path.display()));
    }
    let source = fs::read_to_string(path)
        .map_err(|e| format!("cannot read {}: {}", path.display(), e))?;

    let known_failure = source
        .lines()
        .any(|l| l.starts_with("// KNOWN_FAILURE"));

    // `// BACKEND: interpreter` matches the conformance harness.
    // Default is LLVM.
    let backend = source
        .lines()
        .find_map(|l| l.strip_prefix("// BACKEND: "))
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "llvm".to_string());

    let expected: Vec<&str> = source
        .lines()
        .filter_map(|l| l.strip_prefix("// OUTPUT: "))
        .collect();
    let expected = expected.join("\n");

    let compiler_bin = env!("CARGO_BIN_EXE_algol26");

    // Compile step (LLVM only — interpreter runs directly).
    if backend != "interpreter" {
        let out = Command::new(compiler_bin)
            .arg(path)
            .output()
            .map_err(|e| format!("failed to run compiler: {}", e))?;
        if !out.status.success() {
            // KNOWN_FAILURE means the compile failure is expected —
            // pass silently.
            if known_failure {
                return Ok(());
            }
            return Err(format!(
                "{}: COMPILE FAILED\n{}",
                path.display(),
                String::from_utf8_lossy(&out.stderr)
            ));
        }
    }

    // Run step.
    let actual = if backend == "interpreter" {
        let out = Command::new(compiler_bin)
            .args(["run", "--interpreter"])
            .arg(path)
            .output()
            .map_err(|e| format!("failed to run interpreter: {}", e))?;
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .filter(|l| !l.starts_with('['))
            .collect::<Vec<_>>()
            .join("\n")
            .trim_end()
            .to_string()
    } else {
        let binary = path.with_extension("");
        let out = Command::new(&binary)
            .output()
            .map_err(|e| format!("failed to execute {}: {}", binary.display(), e))?;
        String::from_utf8_lossy(&out.stdout).trim_end().to_string()
    };

    // Verdict.
    if known_failure {
        if actual == expected {
            return Err(format!(
                "{}: KNOWN_FAILURE now PASSES — remove the marker and celebrate",
                path.display()
            ));
        }
        return Ok(());
    }

    if actual != expected {
        return Err(format!(
            "{}: OUTPUT MISMATCH\nexpected:\n{}\nactual:\n{}",
            path.display(),
            expected,
            actual
        ));
    }
    Ok(())
}
